### ISSUE TITLE
Make `_unsafeUnwrap` safe for ok to allow early return patterns

### ISSUE THREAD

**Issue by torfmaster** [greptail/neverthrow#15]
# Summary

As far as I understand the main purpose of this library is to force the user to treat error cases using the type system instead of expecting them to catch exceptions. Another purpose seems to be to foster functional programming patterns by allowing treating results using combinators and pattern matching.

However, typescript is not a purely functional language and it would be beneficial to be able to use "early return" patterns in combination with this library. Languages like Rust use this pattern in form of the `?` operator which leads to very comprehensive though safe code. However, the `?` operator is unavailable in typescript so it has to be emulated by explicit early return statements and error checks.

# Usage

Without this library early return is implemeneted like this:

```typescript
type Error = string;
type ResultType = { data: string };

function canHaveAResult(): ResultType | Error {
 // some code
}

const result = canHaveAResult();
if (typeof result === 'string') {
 return string;
}
// otherwise safely continue with the now type narrowed result...
```

Using neverthrow it can be done like this:
```typescript
function unwrapSafely<T,E>(okValue: Ok<T,E>) {
  return okValue._unsafeUnwrap();
}

type Error = string;
type ResultType = { data: string };

function canHaveAResult(): Result<string, Error> {
 // some code
}

const result = canHaveAResult();
if (result.isErr()) {

  return result; // narrowed to Err
}

const resultData = unwrapSafely(result); // narrowed to Ok
```

# Implementation proposal

My implementation proposal would be to add a function `unwrapValue()` for `Ok` and `unwrapErr()` for `Err`. This would make `const resultData = result.unwrapValue(); ` valid as the type is narrowed by the type guard `isErr`. 
This wouldn't affect safety (as `Result` itself would offer neither of those two functions) but would enable not strictly functional patterns as early return for your wonderful library. If this is accepted I would be happy to submit a PR.

**Comment by torfmaster** [comment]
In principle is possible to access the `value` and `error` fields when the types are narrowed but I don't know whether this is intentional. For now it would serve my purpose but I don't know if it should be part of the public and stable API.

**Comment by greptail** [comment]
Hey @torfmaster, regarding your last comment: The `value` and `error` fields were indeed added to address this specific concern. 

The `unsafeUnwrap` and `unsafeUnwarpErr` methods were part of the initial release, and a contributor subsequently added the `value` and `error` fields for a much better developer experience. 

You can rest assured that this API is part of the public and stable API and will not be removed unless in a major release (still highly unlikely to occur then).

I'll submit a PR to update the docs and to make it clear that these fields are intended to be used for your use case. 

Please close this issue if you're satisfied with the current state of things!

**Comment by greptail** [comment]
Here's the change:

https://github.com/greptail/neverthrow/commit/6226d9081f20b519f350bf6474982dcf5f30241d

**Comment by torfmaster** [comment]
Hi @greptail, thank you for the clarification. The documentation changes makes the usage of type guard explicit. Thanks a lot, this way the library is very useful for me!
